src/user/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView
from . import views

app_name = 'user'

urlpatterns = [
    path("/", views.landing, name="landing"),
    path("updateinfo/", views.update_info, name="update_info"),
    path("plan/", views.plan, name="plan"),
    path("department_view/", views.department_view, name="department_view"),
    path("course_search/", views.course_search, name="course_search"),
    re_path(r'^accounts/profile/$', RedirectView.as_view(url='/landing', permanent=True), name='profile_redirect'),
    path("view_major_courses/", views.view_major_courses, name="view_major_courses"),
]

src/webyte/urls.py
from django.contrib import admin
from django.urls import include, path
import user.views as views

urlpatterns = [
    path("", views.index, name="index"),
    path("advisor_login/", views.advisor_login, name='advisor_login'),
    path("user/", include("user.urls")),
    path("admin/", admin.site.urls),
    path("landing/", views.landing),
    path("plan/", views.plan, name="plan"),
    path("updateinfo/", views.update_info, name="update_info"),
    path('accounts/', include('allauth.urls')),
    path("plan/", views.plan, name="plan"),
    path('remove_course/', views.remove_course, name='remove_course'),
    path('course_search/', views.course_search, name='course_search'),
    path("view_major_courses/", views.view_major_courses, name="view_major_courses"),

]

src/user/forms.py
from django import forms
from .models import Student, Course

from django import forms
from .models import Student

class StudentUpdateForm(forms.ModelForm):
    SCHOOL_CHOICES = [('', 'Select School')] + [
        ('MCAS', 'Morrissey College of Arts & Sciences'),
        ('LYNCH', 'Lynch School of Education & Human Development'),
        ('CSOM', 'Carroll School of Management'),
        ('CSON', 'Connell School of Nursing'),
    ]

    YEAR_CHOICES = [('', 'Select Year')] + [
        ('F2020', 'Fall 2020'),
        ('S2020', 'Spring 2020'),
        ('F2021', 'Fall 2021'),
        ('S2021', 'Spring 2021'),
        ('F2022', 'Fall 2022'),
        ('S2022', 'Spring 2022'),
        ('F2023', 'Fall 2023'),
        ('S2023', 'Spring 2023'),
    ]

    DEPARTMENT_CHOICES = [('', 'Select Department')] + [
        ('ART', 'Art, Art History, and Film'),
        ('ACCT', 'Accounting'),
        ('BIO', 'Biology'),
        ('CHEM', 'Chemistry'),
        ('COMM', 'Communications'),
        ('CS', 'Computer Science'),
        ('ECON', 'Economics'),
        ('HCE', 'Engineering'),
        ('ENG', 'English'),
        ('FIN', 'Finance'),
        ('HIST', 'History'),
        ('MATH', 'Mathematics'),
        ('MKT', 'Marketing'),
    ]

    MAJOR_CHOICES = [('', 'Select Major')] + [
        ('UNDEC', 'Undecided'),
        ('ART', 'Art, Art History, and Film'),
        ('ACCT', 'Accounting'),
        ('BIO', 'Biology'),
        ('CHEM', 'Chemistry'),
        ('COMM', 'Communications'),
        ('CS/BA', 'Computer Science, B.A.'),
        ('CS/BS', 'Computer Science, B.S.'),
        ('ECON', 'Economics'),
        ('HCE', 'Engineering'),
        ('ENG', 'English'),
        ('FIN', 'Finance'),
        ('HIST', 'History'),
        ('MATH', 'Mathematics'),
        ('MKT', 'Marketing'), 
        ('AADS', 'African Diaspora Studies')
    ]

    SECOND_MAJOR_CHOICES = [('', 'Select Major')] + [
        ('ART', 'Art, Art History, and Film'),
        ('ACCT', 'Accounting'),
        ('BIO', 'Biology'),
        ('CHEM', 'Chemistry'),
        ('COMM', 'Communications'),
        ('CS/BA', 'Computer Science, B.A.'),
        ('CS/BS', 'Computer Science, B.S.'),
        ('ECON', 'Economics'),
        ('HCE', 'Engineering'),
        ('ENG', 'English'),
        ('FIN', 'Finance'),
        ('HIST', 'History'),
        ('MATH', 'Mathematics'),
        ('MKT', 'Marketing'),
        ('', 'None'),
    ]

    MINOR_CHOICES = [('', 'Select Minor')] + [
        ('ART', 'Art, Art History, and Film'),
        ('ACCT', 'Accounting'),
        ('BIO', 'Biology'),
        ('CHEM', 'Chemistry'),
        ('COMM', 'Communications'),
        ('CS', 'Computer Science'),
        ('ECON', 'Economics'),
        ('HCE', 'Engineering'),
        ('ENG', 'English'),
        ('FIN', 'Finance'),
        ('HIST', 'History'),
        ('MATH', 'Mathematics'),
        ('MKT', 'Marketing'),
        ('', 'None'),
    ]

    school = forms.ChoiceField(choices=SCHOOL_CHOICES, required=False)
    start = forms.ChoiceField(choices=YEAR_CHOICES, required=False)
    department = forms.ChoiceField(choices=DEPARTMENT_CHOICES, required=False)
    major1 = forms.ChoiceField(choices=MAJOR_CHOICES, required=False)
    major2 = forms.ChoiceField(choices=SECOND_MAJOR_CHOICES, required=False)
    minor1 = forms.ChoiceField(choices=MINOR_CHOICES, required=False)
    minor2 = forms.ChoiceField(choices=MINOR_CHOICES, required=False)

    class Meta:
        model = Student
        fields = ['school', 'start', 'department', 'major1', 'major2', 'minor1', 'minor2']


    def __init__(self, *args, **kwargs):
        super(StudentUpdateForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()

        return instance


class SelectCourseForm(forms.ModelForm):
    SEMESTER_CHOICES = [
        ('freshman_fall', 'Freshman Fall'),
        ('freshman_spring', 'Freshman Spring'),
        ('sophomore_fall', 'Sophomore Fall'),
        ('sophomore_spring', 'Sophomore Spring'),
        ('junior_fall', 'Junior Fall'),
        ('junior_spring', 'Junior Spring'),
        ('senior_fall', 'Senior Fall'),
        ('senior_spring', 'Senior Spring'),
    ]

    # ModelChoiceField is used when we are selecting objects from a model,
    # as opposed to regular elements in a regular list (ChoiceField)
    course = forms.ModelChoiceField(queryset=Course.objects.all())
    semester = forms.ChoiceField(choices=SEMESTER_CHOICES, required=True)

    class Meta:
        model = Student
        fields = ['course', 'semester']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(SelectCourseForm, self).__init__(*args, **kwargs)
        if user is not None and user.major1 is not None:
            self.fields['course'].queryset = Course.objects.filter(department=user.major1)

class DepartmentSearchForm(forms.Form):
    department = forms.ChoiceField(choices=[('all', 'All Departments'), ('CSCI', 'Computer Science'), ('ECON', 'Economics')])

src/user/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Sum, Case, When, Value, IntegerField, F
import logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

from .models import User, Student, Advisor, Administrator, Plan, Course, CS_Major_BA, CS_Major_BS, CS_Major_Core, Econ_major, ScienceComponent
import uuid
import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .utils import get_prereqs_from_api, sort_plans_by_current, get_full_courses_dict
from .forms import SelectCourseForm, DepartmentSearchForm
from django.http import HttpResponseRedirect
from django.urls import reverse
# for prereq JSON solution
import json


# accessing the website with / renders the login.html page
def index(request):
    logger.debug('Debug message')
    logger.info('Info message')
    return render(request, 'user/login.html')

# accessing the website with /advisor_login/ renders the advisor_login.html page
def advisor_login(request):
    return render(request, 'user/advisor_login.html')

from django.shortcuts import render

# global constant for SEMESTERS bc these never change and are used in 2 diff views
SEMESTERS = ['freshman_fall', 'freshman_spring', 'sophomore_fall', 
             'sophomore_spring', 'junior_fall', 'junior_spring', 
             'senior_fall', 'senior_spring']

# Landing page
def landing(request):
    # This assumes you have a way to link your User to a Student, e.g., via email or a OneToOneField
    user = request.user

    context = {}
    # if user exists in Admin table
    if User.get_user(user.email, Administrator):
        administrator = Administrator.objects.get(email=user.email)
        context = {
            'user': user,
            'user_type': 'administrator',
            'name': administrator.name,
        }
    
    # if user exists in Advisor table
    elif User.get_user(user.email, Advisor):
        advisor = Advisor.objects.get(email=user.email)

        context = {
            'user': user,
            'user_type': 'advisor',
            'name': advisor.name,
            'school': advisor.school,
        }
    
    # if user is neither Advisor nor Admin, they are Student
    else:
        student = User.get_user(user.email, Student)

        # if user isn't in the Student table, add them
        if not student:
            new_student = Student(name=user.first_name, email=user.email)
            new_student.save()

            student = Student.objects.get(email=user.email)

        # in this instance redirect takes a view as its parameter
        if not student.first_login_completed:
            return redirect('user:update_info') # redirect users to update info upon first login
    
        # Progress Bar Tings
        # Fetch the current plan for the student, assuming they only have one plan for simplicity
        # Need to update with main plan ***

        bar_progress = 0  # Default progress

        current_plan = Plan.objects.filter(user=student).first()
        
        if current_plan:
            MAX_CREDITS = 120
            courses = get_full_courses_dict(SEMESTERS, current_plan) if current_plan else {}
            total_credits = 0
            for x in courses:
                    for y in courses[x]:
                        if y:
                            course_data = fetch_data_from_api(y)
                            if course_data:
                                if course_data[0]['course']['creditOptionIds']:
                                    total_credits += float(course_data[0]['course']['creditOptionIds'][0][-3:])
            bar_progress = total_credits / MAX_CREDITS * 100
            bar_progress = int(bar_progress)
            # print(bar_progress, type(bar_progress), total_credits, type(total_credits))
        else:
            total_credits = 0

        context = {
            'user': user,
            'user_type': 'student',
            'name': student.name,
            'school': student.school,
            'majors': [student.major1, student.major2],
            'minors': [student.minor1, student.minor2],
            'total_credits': total_credits, #total credits completed from mainish plan
            'bar_progress': bar_progress, #this is for what percent of progress bar it should take up
        }

    return render(request, 'user/landing.html', context)

from .forms import StudentUpdateForm, SelectCourseForm


def update_info(request):
    user = request.user
    student = Student.objects.get(email=user.email)

    if request.method == 'POST':
        form = StudentUpdateForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            student.first_login_completed = True
            student.save()
    else:
        form = StudentUpdateForm(instance=student)

    return render(request, 'user/update_info.html', {'form': form, 'student': student})



# helper function used in plan
def calculate_major_requirements_progress(student, courses):
    major = student.major1
    fulfilled_requirements_count = 0
    if major[0:2] == 'CS':
        total_major_requirements = len(CS_Major_Core._meta.get_fields()[3:])
        core_list = [field.name for field in CS_Major_Core._meta.get_fields()[3:]]
        for x in courses:
            for y in courses[x]:
                if y in core_list:
                    fulfilled_requirements_count += 1
        if major == 'CS/BS':
            total_major_requirements += len(CS_Major_BS._meta.get_fields()[1:])
            bs_list = [field.name for field in CS_Major_BS._meta.get_fields()[1:]]
            for x in courses:
                for y in courses[x]:
                    if y in bs_list:
                        fulfilled_requirements_count += 1
        if major == 'CS/BA':
            total_major_requirements += len(CS_Major_BA._meta.get_fields()[1:])
            ba_list = [field.name for field in CS_Major_BA._meta.get_fields()[1:]]
            for x in courses:
                for y in courses[x]:
                    if y in ba_list:
                        fulfilled_requirements_count += 1
        return round((fulfilled_requirements_count / total_major_requirements) * 100) if total_major_requirements else 0
    else: # Econ
        total_major_requirements = len(Econ_major._meta.get_fields()[1:])
        econ_list = [field.name for field in Econ_major._meta.get_fields()[1:]]
        for x in courses:
            for y in courses[x]:
                if y in econ_list:
                    fulfilled_requirements_count += 1
        return (fulfilled_requirements_count / total_major_requirements) * 100 if total_major_requirements else 0

def plan(request):
    user = request.user

    # Determine if the user is an advisor
    advisor = User.get_user(user.email, Advisor)
    if advisor:

        # let the view know if student has been changed
        student_change = False

        # if there is no current student yet 
        if 'cur_student' not in request.session:
            request.session['cur_student'] = advisor.students.first().email

        if request.method == 'POST':
            if 'student-select' in request.POST:
                request.session['cur_student'] = request.POST.get('student-select')
                student_change = True
            if 'plan-select' in request.POST:
                request.session['cur_plan_id'] = request.POST.get('plan-select')

        # all students the advisor has access to, by email
        students = advisor.students.all()
        student_emails = [student.email for student in students]

        # the current student the advisor is looking at
        student = Student.objects.filter(email=request.session.get('cur_student'))[0]

        # all plans for the current student
        plans = Plan.objects.filter(user=student)

        # if this is the first time you look at a student, or you have
        # flipped between students, initialize the cur_plan_id to their default (main) plan
        if 'cur_plan_id' not in request.session or student_change:
            request.session['cur_plan_id'] = str(plans.first().id)

        cur_plan_id = request.session.get('cur_plan_id')

        # the current plan the advisor is looking at
        current_plan = Plan.objects.filter(id=cur_plan_id).first()

        courses = get_full_courses_dict(SEMESTERS, current_plan)
        
        plans = sort_plans_by_current(student, current_plan)

        # make sure current student is displayed first
        student_emails.remove(student.email)
        student_emails.insert(0, student.email)
        
        context = {
            'user': user,
            'name': advisor.name,
            'school': advisor.school,
            'plans': plans,
            'cur_plan': current_plan,
            'students': student_emails,
            'courses': courses,
        }
        
        return render(request, 'user/plan_view_advisor.html', context)

    # If not an advisor, assume the user is a student (or handle other roles)
    student = get_object_or_404(Student, email=user.email)
    # if any of the required fields are not filled out, redirect to update_info
    if not all([student.school, student.department, student.start, student.major1]):
        return redirect('update_info')

    user_plans = Plan.objects.filter(user=student)
    major = student.major1
    major_needs = []
    # Existing logic for handling plan operations
    if request.method == 'POST':
        if 'create_plan' in request.POST:
            plan_name = request.POST.get('new_plan_name', 'New Plan')
            new_plan = Plan.objects.create(user=student, name=plan_name)
            request.session['cur_plan_id'] = str(new_plan.id)
            return redirect('user:plan')

        elif 'clear_plan' in request.POST:
            plan = get_object_or_404(Plan, id=request.session['cur_plan_id'])
            plan.delete()

src/templates/user/add_course.html
{% include 'user/plan_view.html' %}
<body>
    <div class="left-sidebar-grid">
        <div id="add-course-modal" class="modal">
            <div class="modal-content">
                <!-- Removed the span with the close-button class -->
                <div id="course-form-container">
                    <form method="post">
                        {% csrf_token %}
                        <div id="course-form-container">
                        <form method="post">
                            {% csrf_token %}
                            {{ form }}
                            <button type="submit" style="color: black">Select</button>
                        </form>
                        </div>
                        {% if repeat_warning %}
                        <div id="course-form-container">
                            This course is already in your plan!
                        </div>
                        {% endif %}
                        {% if course_warning %}
                        <div id="course-form-container">
                            You can't add more than 5 courses to a single semester!
                        </div>
                        {% endif %}
                        {% if prereq_warning %}
                        <div id="course-form-container">
                            WARNING: You do not have the pre-requisites for this course
                            <div>To take this course you must have already taken:</div>
                            {% for course_code in missing_prereqs %}
                                <div>{{ course_code }}</div>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <!--<input type="text" name="search" placeholder="Search courses..." class="search-input">
                        <button type="submit" class="search-button" style="color: black">Search</button>-->
                        
                        <!--<div class="filter-section">
                            <h3>Select Semester</h3>
                            <div class="semester-selection-container">
                                <select name="semester" class="semester-select">
                                    <option value="FF">Freshman Fall</option>
                                    <option value="FS">Freshman Spring</option>
                                    <option value="SOF">Sophomore Fall</option>
                                    <option value="SOS">Sophomore Spring</option>
                                    <option value="JF">Junior Fall</option>
                                    <option value="JS">Junior Spring</option>
                                    <option value="SEF">Senior Fall</option>
                                    <option value="SES">Senior Spring</option>
                                </select>
                            </div>
                        </div>-->

                        <div class="filter-section">
                            <h3>Subject Area</h3>
                            <div class="subject-area-container">
                                <label><input type="checkbox" name="subject_area" value="CSCI"> CSCI - Computer Science</label><br>
                                <label><input type="checkbox" name="subject_area" value="ECON"> ECON - Economics</label><br>
                                <label><input type="checkbox" name="subject_area" value="CHEM"> CHEM - Chemistry</label><br>
                                <label><input type="checkbox" name="subject_area" value="EESC"> EESC - Earth Science</label><br>
                                <!-- More subject areas -->
                            </div>
                        </div>
                        
                        <div class="filter-section">
                            <h3>Course Level</h3>
                            <div class="course-level-container">
                                <label><input type="checkbox" name="course_level" value="1000"> 1000+</label><br>
                                <label><input type="checkbox" name="course_level" value="2000"> 2000+</label><br>
                                <label><input type="checkbox" name="course_level" value="3000"> 3000+</label><br>
                                <!-- More levels -->
                            </div>
                        </div>
                    </form>
                    <a href="{% url 'user:plan' %}" class="cancel-button">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</body>

src/templates/user/advisor_login.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>EaglePlan - Your Academic Planner</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/landing/eagleplan.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">EaglePlan</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        </ul>
      </div>
    </nav>

    <div class="container mt-5 text-center">
      <h1>Advisor Login</h1>
      <p>Login with your bc.edu email to manage advisee plans.</p>
      <img src="https://cdn.glitch.global/f1f98189-106c-457f-ab2f-965094d0d0cc/eagleapps-logo-header.svg?v=1708357418144" alt="Descriptive Text" class="login-logo mb-3" />
      <button class="btn btn-lg btn-google" onclick="location.href='/accounts/google/login/'" style="background: #4285F4; color: white;">Login with Google</button>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

src/templates/user/course_search.html
{% include 'user/navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Department View</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .card-container {
            overflow-y: auto; /* Enable vertical scrolling */
        }
    </style>
</head>
<body>
    <h3>Search Course by Department</h3>
    <form method="post">
      {% csrf_token %}
        <select name="department">
            <option value="CSCI">Computer Science</option>
            <option value="ECON">Economics</option>
            <option value="MATH">Math</option>
            <option value="THEO">Theology</option>
            <option value="ENVS">Environmental Studies</option>
            <option value="CHEM">Chemistry</option>
            <option value="BIOL">Biology</option>
            <option value="PHYS">Physics</option>
            <option value="THEO">Theology</option>
            <option value="AADS">African Diaspora Studies</option>
            <option value="ARTS">Studio Art</option>
            <option value="ENGL">English</option>
            <option value="HIST">History</option>
        </select>
        <button type="submit">Search</button>
    </form>
    {% if messages %}
          {% for message in messages %}
              <div class="alert alert-warning" role="alert">
                  {{ message }}
              </div>
          {% endfor %}
          {% endif %}
    {% if data %}
    <h4>Search Results for {{ department }}</h4>
    <div class="card-container">
        {% for item in data %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ item.course.name }} </h5>
                    <p class="card-text">{{ item.course.descr.plain }}</p>
                    {% if item.course.creditOptionIds %}
                    <p class="card-text">Number of Credits: {{ item.credits }}</p>
                    {% else %}
                    <p class="card-text">Number of Credits: N/A</p>
                    {% endif %}
                    {% if item.prereqs %}
                      <p class="card-text" style="color: red">You will not be able to add to plan unless you also have the following: {{ item.prereqs|join:", " }}</p>
                    {% else %}
                        <p class="card-text" style="color: red">Prerequisites: None</p>
                    {% endif %}    
                    {% if repeat_warning %}
                      <p class="card-text" style="color: red">Warning: this course is already in your plan</p>
                    {% endif %}
                   <form method="post">
                      {% csrf_token %}
                      
                      <select name="semester">
                          <option value="freshman_fall">Freshman Fall</option>
                          <option value="freshman_spring">Freshman Spring</option>
                          <option value="sophomore_fall">Sophomore Fall</option>
                          <option value="sophomore_spring">Sophomore Spring</option>
                          <option value="junior_fall">Junior Fall</option>
                          <option value="junior_spring">Junior Spring</option>
                          <option value="senior_fall">Senior Fall</option>
                          <option value="senior_spring">Senior Spring</option>
                      </select>
                      <input type="hidden" name="new_course_code" value="{{ item.course.courseCode }}">
                      <input type="hidden" name="new_course_credits" value="{{ item.credits }}">
                      <button type="submit" style="color: black">Add Course to Plan</button>
                    </form>
                    {% if repeat_warning %}
                    <div id="course-form-container">
                        This course is already in your plan!
                    </div>
                    {% endif %}
                    {% if course_warning %}
                    <div id="course-form-container">
                        You can't add more than 5 courses to a single semester!
                    </div>
                    {% endif %}
                    {% if prereq_warning %}
                    <div id="course-form-container">
                        WARNING: You do not have the pre-requisites for this course
                        <div>To take this course you must have already taken:</div>
                        {% for course_code in missing_prereqs %}
                            <div>{{ course_code }}</div>
                        {% endfor %}
                    </div>
                    {% endif %}
                  </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}
</body>
</html>

src/templates/user/navbar.html
<!-- templates/shared/navbar.html -->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>EaglePlan - Your Academic Planner</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="../../static/css/sitewide/navbar_style.css" />
  </head>
  <!-- templates/shared/navbar.html -->
  <nav class="navbar navbar-expand-lg navbar-dark">
    <img
      src="https://cdn.glitch.global/f1f98189-106c-457f-ab2f-965094d0d0cc/eagleapps-logo-header.svg?v=1708357418144"
      alt="bc-logo"
      id="header-logo"
    />
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'user:landing' %}">Eagle Plan</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a
              class="nav-link {% if request.resolver_match.url_name == 'landing' %}active{% endif %}"
              href="{% url 'user:landing' %}"
              >Home</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if request.resolver_match.url_name == 'update_info' %}active{% endif %}"
              href="{% url 'user:update_info' %}"
              >Profile</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if request.resolver_match.url_name == 'plan' %}active{% endif %}"
              href="{% url 'user:plan' %}"
              >Build Plan</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if request.resolver_match.url_name == 'course_search' %}active{% endif %}"
              href="{% url 'user:course_search' %}"
              >Search Courses</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>
</html>

src/templates/user/navbar_admin.html
<!-- templates/shared/navbar.html -->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>EaglePlan - Your Academic Planner</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="../../static/css/sitewide/navbar_style.css" />
  </head>
  <!-- templates/shared/navbar.html -->
  <nav class="navbar navbar-expand-lg navbar-dark">
    <img
      src="https://cdn.glitch.global/f1f98189-106c-457f-ab2f-965094d0d0cc/eagleapps-logo-header.svg?v=1708357418144"
      alt="bc-logo"
      id="header-logo"
    />
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'user:landing' %}">Eagle Plan</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a
              class="nav-link {% if request.resolver_match.url_name == 'landing' %}active{% endif %}"
              href="{% url 'user:landing' %}"
              >Home</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if request.resolver_match.url_name == 'department_view' %}active{% endif %}"
              href="{% url 'user:department_view' %}"
              >Department View</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>
</html>